/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example.kafka.dto;
public class AlertDto2 {
  private long id;
  private long tenantId;
  private String name;

  public void setId(long id) {
    this.id = id;
  }
  public void setTenantId(long tenantId) {
    this.tenantId = tenantId;
  }
  public void setName(String name) {
    this.name = name;
  }

  public long getId() {
    return id;
  }
  public long getTenantId() {
    return tenantId;
  }
  public String getName() {
    return name;
  }

}